apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xop5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xop5
    app.kubernetes.io/part-of: tkwch-fix-0075-0022-app
  name: devfile-sample-xop5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xop5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xop5
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0022-tenant/tkwch-fix-0075-0022-app/devfile-sample-xop5@sha256:484c9454c66fd3b341bdeadedd63e9ded3f17a0c1ce53a649092135b4bb5dcd3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
